[project]
name = "Mistrz_Klawiatury"
version = "0.1"
dependencies = [
  "pygame-ce>=2.4.1",
  "pygame-gui==0.6.10",
]
requires-python = ">=3.11"

readme = "README.md"

[project.optional-dependencies]
test = ["pytest>=8.2"]
bulid = ["pyinstaller>=6.8"]